# The URL the site will be built for
base_url = "https://claytonwramsey.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
feed_filenames = ["rss.xml", "atom.xml"]

[markdown]
smart_punctuation = true

[markdown.highlighting]
style = "class"
light_theme = "bauhaus-light"
dark_theme = "bauhaus-dark"
extra_themes = ["highlight_themes/bauhaus-light.json", "highlight_themes/bauhaus-dark.json"]

[markdown.math]
engine = "typst"
format = "mathml"

[extra]
# Put all your custom variables here
